[package]
name = "wasm-glue"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.100", default-features = false, features = ["std"] }

[lints]
workspace = true
